export { default as LoginPage } from './Login'
export { default as AboutPage } from './About'
export { default as RegistrationPage } from './Registration'
export { default as AccountPage } from './Account'
export { default as GenresPage } from './Genres'
export { default as MainPage } from './Main'
export { default as UsersPage } from './Users'
export { default as CreatePage } from './Create'