export { default as LoginPage } from './Login'
export { default as AboutPage } from './About'
export { default as RegistrationPage } from './Registration'
export { default as AccountPage } from './Account'
export { default as GenresPage } from './Genres'